### ISSUE TITLE
对账双方字段映射配置说明与代码逻辑不符

### ISSUE THREAD

**Issue by xxmlovezw** [WeBankBlockchain/Data-Reconcile#12]
对账配置文件中规定对账双方字段映射这样配置：
         reconcile.fieldMapping.业务方字段=对账方字段
实际代码逻辑：
         在ReconcileExecutorImpl.execute()方法中
                      for (Map.Entry<String, String> entry : bcFieldMap.entrySet()) { // reconcile.fieldMapping.数据导出表字段 = 业务方字段名
                String key = entry.getKey();
                if (fieldMapping.containsKey(key)) {
                    String keyMapping = fieldMapping.get(key);
                    String value = entry.getValue();
                    String valueMapping = busFieldMap.get(keyMapping);
                    if (value != null && !value.equals(valueMapping)) {
                        builder.append(key).append(" = ").append(entry.getValue()).append(", ")
                                .append(keyMapping).append(" = ").append(valueMapping).append("; ");
                        reconcileResult.setSuccess(false);
                    }
                }
            }

**Comment by wangyue168git** [comment]
建议再阅读下代码，比较两者逻辑，最终是一致的

**Comment by saiwg** [comment]
我也发现了这个问题，例子中配置 reconcile.fieldMapping.业务方字段=数据库字段
实际上 reconcile.fieldMapping.数据库字段=业务方字段 才能正确执行

**Comment by wangyue168git** [comment]
经再次确认，确实存在该问题，已修改

**Comment by dalaocu** [comment]
> 经再次确认，确实存在该问题，已修改

https://github.com/WeBankBlockchain/Data-Reconcile/commit/38ddcfb13847eff29e2656d81ca9b2535075c324
